export const ROLES = {
  SHAREHOLDER: 'SHAREHOLDER',
  PROXY_REPRESENTATIVE: 'PROXY_REPRESENTATIVE',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  AUDITOR: 'AUDITOR',
};

export const ROLE_LIST = Object.values(ROLES);
